---
title: "Projects description"
author: "Alexander Sirotkin"
date: "18 02 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
 Данный файл предназначен для внесения проектов.
 Ниже приведен шаблон которым нужно пользоваться. Копируете блок от "xxx" до "xxx" и вносите необходимую информацию.

xxx

## название проекта  

Здесь должно быть краткое описание проекта, примерно один абзац.
 
Список участников:

1. Фио (специальность)
2. Фио (специальность)
...
 
Дополнительные коментарии и пожелания к другим участникам.

xxx


Здесь должно быть краткое описание проекта, примерно один абзац.
 
 В целом, проект - это рекомендательная система, которая подбирает наиболее подходящий портфель для инвестирования на бирже (не трейдинг, а именно инвестирование).
На данном этапе задумка заключает в себе систему, которая поможет выбрать наилучший вариант для инвестора (даже не особо смыслящего в риске). Грубо говоря, процесс следующий: "укажите располагаемую Вами сумму, какое у Вас отношение к риску, укажите интервал для инвестирования".
Наверняка этот вариант будет усилен еще как-либо.
Группа уже состоит из трех человек (пока что только экономисты, так как, сами понимаете, эта тема довольно специфичная, но интересная). Поэтому, если Вы разрешите данный проект, то мы опубликуем на форуме набор 2 человек (вероятнее всего с каких-либо других ОП).
 
Список участников:

1. Ким Павел (Экономика)
2. Лопушанский Денис (Экономика)
3. Орлова Дарья (Экономика)
...
 
Дополнительные коментарии и пожелания к другим участникам.

xxx

Здесь должно быть краткое описание проекта, примерно один абзац.
 
Описание добавим чуть позже... Но это будет рекомендации постов в ВК на основе текст майнинга.
 
Список участников:

1. Худяков Юрий (Социология)
2. Будаева Александра (Социология)
3. Письменная Екатерина (Менеджмент)
4. ??? инкогнито (надеемся вы поможете) ???
5. ??? инкогнито (надеемся вы поможете) ???


xxx

## Лучшая шаурма в СПб и ЛО (название может поменяться...)

Рекомендательная система кафе в спб и ло с шаурмой.
На основе предпочтений (понравилось там-то, люблю побольше соуса или что-то в этом роде) выдаёт места, которые Вам стоит посетить.
Дату тянем с паблика вк - возможность, теоритически, есть.
 
Список участников:

1. Руслан Угланов (политология)
2. Никита Веселов (ГМУ)
3. Глеб Албегов (политология)
4. Василина Чарушина (социология)
5. Руслан Ефимов (менеджмент)
6. Даниил Зуев (ГМУ)
 

xxx


xxx

## steam database recommendation system 

Рекомендательная система игр (платформа steam).
Ссылка на источник датасета: https://www.reddit.com/r/MachineLearning/comments/3q8w47/here_are_some_free_datasets_of_video_game_reviews/
+ еще что-нибудь можем достаточно
 
Список участников:

1. Кузьмин Павел Григорьевич (экономика)
2. Шикин Антон Александрович (экономика)
3. Шабурова Дарья Андреевна (экономика)
4. Козырев Захар Антонович (менеджмент)

xxx

## Рекомендательная система в области логистики 

Данная система будет основываться на базе крупных и средних экспедиторов и грузоперевозчиков и будет советовать оптимального перевозчика основываясь на следующих параметрах: вес груза, дальность перевозки, стоимость перевозки, время транспортировки, рекомендуемый транспорт. Число параметров может возрасти. 

Список участников: 

1. Аникина Наталья (Логистика и УЦП), 
2. Кудрявцев Дмитрий (Логистика и УЦП), 
3. Сипинев Глеб (Логистика и УЦП), 
4. Усович Ксения (Логистика и УЦП), 
5. Шарков Илья (Логистика и УЦП). 

Поскольку наша рекомендательная система не является общенаправленной, а имеет отношение только к одной образовательной программе (Логистика), просим вас принять это во внимание во время принятия решения). 

xxx

xxx

## Рекомендательная система для сериалов южно-корейского производства 

Рекомендательная система по дорамам (южно-корейским сериалам) на основе данных с myshows.ru 
Система будет выдавать рекомендации пользователям сайта на основе просмотренных дорам и их оценок.


Список участников: 

1. Максимова Мария (Экономика), 
2. Порозова Вероника (Экономика), 
3. Гасанова Сабина (Менеджмент), 
4. Ермакова Катерина  (Востоковедение), 
5. Кокунина Анастасия (Логистика). 

xxx